// import { NgModule } from '@angular/core';
//
// import { FcdetailComponent }   from './fcdetail.component';
// import {RouterModule, Routes} from "@angular/router";
//
// const fcdetailRoutes: Routes = [
//   { path: '', component: FcdetailComponent }
// ];
//
// @NgModule({
//   imports: [
//     RouterModule.forChild(fcdetailRoutes)
//   ],
//   declarations: [
//     FcdetailComponent
//   ]
// })
// export class FcdetailModule {}
